project:
  type: website

# Output configuration for the website
output:
  html_document:
    self_contained: true
    toc: true # Optional: To include a table of contents

# Configuration for site navigation
site:
  title: "Diabetes Project Links"  # Replace with your title
  navbar:
    right:
      - text: "EDA"
        href: EDA.html
      - text: "Modeling"
        href: Modeling.html
